package com.bedmaster.module.module_9.dto;

import com.bedmaster.module.module_9.enums.Category;

// Represents the JSON body the client sends when creating a notification.
// notificationId is excluded — it is auto-generated by the database.
// status is excluded — it always defaults to UNREAD on creation.
// createdDate is excluded — it is stamped automatically by @PrePersist on the entity.
public class NotificationRequestDTO {

    private Long userId;       // ID of the user who should receive this notification
    private String message;    // Notification text to display in the UI
    private Category category; // Workflow category (ASSIGNMENT, CLEANING, ISOLATION, TRANSFER, DISCHARGE)

    // No-arg constructor required by Jackson to deserialize the incoming JSON request body.
    public NotificationRequestDTO() {}

    public NotificationRequestDTO(Long userId, String message, Category category) {
        this.userId = userId;
        this.message = message;
        this.category = category;
    }

    public Long getUserId() { return userId; }
    public void setUserId(Long userId) { this.userId = userId; }

    public String getMessage() { return message; }
    public void setMessage(String message) { this.message = message; }

    public Category getCategory() { return category; }
    public void setCategory(Category category) { this.category = category; }
}
